import type { Metadata } from "next";
import { Fragment } from "react";

export const metadata: Metadata = {
  title: "Pickup Roster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
      <header className="h-8">
        <h1>Court Master</h1>
      </header>

      <div className="grow w-full flex items-center justify-center">{children}</div>

      <footer>
        <p>Build: v1.0.0</p>
      </footer>
    </Fragment>
  );
}
